### ISSUE TITLE
Can I create a tun under non-root user?

### ISSUE THREAD

**Issue by alex-chan** [montag451/pytun#10]
When I create a tun in non-root I got a "Operation not permitted" error, can it be run under non-root user?
```
>>> from pytun import TunTapDevice as ttd
>>> a = ttd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pytun.Error: [Errno 1] Operation not permitted
```

**Comment by montag451** [comment]
A process only needs the CAP_NET_ADMIN capability to create TUN/TAP devices (see [capabilities(7)](http://man.cx/capabilities(7))). However to grant such capability to a process you will need admin rights on the system. The simplest way to do that is to use [setcap(8)](http://man.cx/setcap(8)) on the interpreter executable (you need to be root to do that):
```shell
setcap cap_net_admin=+pe /path/to/the/python/interpreter
```
Once done, you will be able to create TUN/TAP device as a normal user using the modified interpreter executable.

PS: you shouldn't modify the interpreter provided with your OS but instead create a virtualenv with --always-copy and execute the previous command on the interpreter created in your virtualenv

**Comment by montag451** [comment]
I will close this issue since it's not related to pytun

**Comment by alex-chan** [comment]
Thank you very much, it works!

**Comment by montag451** [comment]
You are welcome !
