### ISSUE TITLE
Something wrong with fragmentation

### ISSUE THREAD

**Issue by seiferteric** [montag451/pytun#13]
I saw an issue with my own script, but then reproduced it using the script in test/test_tap.py.

I set up a tunnel between two machines with mtu of 1500, and it appears to work, but if I ping with a payload above a certain size (1458) it fails. You can use `ping -c 1 -s 1459 <ip>` to test. Also, if I ssh to the host over the tunnel, I can log in okay, but if I do a `ls -l` in a large directory (like /etc) it will hang because the packets get above that threshold.

**Comment by lxylxy123456** [comment]
When you read by `tun.read(tun.mtu)`, there is some prefix in the data. On my computer, it is 64 bits / 4 bytes. You can see it through `ifconfig`'s `prefixlen`. So you should read by `tun.read(tun.mtu + 4)` or more. I hope that pytun can add support to that. 

    $ ifconfig tun0
    tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
            inet ...
            inet6 ...  prefixlen 64  scopeid 0x20<link>
    $

**Comment by montag451** [comment]
I don't think your problem is related to pytun so I will close this issue
