### ISSUE TITLE
pytun.Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by diakbar** [montag451/pytun#14]
I tried this on Ubuntu for Windows, but I got following weird error:

```
>>> from pytun import TunTapDevice, IFF_TAP
>>>
>>> tap = TunTapDevice(flags=IFF_TAP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pytun.Error: [Errno 2] No such file or directory
>>> tun = TunTapDevice()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pytun.Error: [Errno 2] No such file or directory
>>> TunTapDevice
```

Am I missed something?

**Comment by montag451** [comment]
Hi,

The `tun` module is maybe not loaded. Can you post the result of the command:
```bash
lsmod | grep tun
```

**Comment by diakbar** [comment]
here's the output:
`libkmod: ERROR ../libkmod/libkmod-module.c:1655 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory`

i think I know now that ubuntu for windows 10 not include lsmod with limited hardware access.
based on this article 
https://www.webreflection.co.uk/blog/2016/04/13/bash-on-ubuntu-on-windows

I'm windows user for my main work, just curious if pytun available for python Windows?

**Comment by montag451** [comment]
I'm closing this issue because it's not related to `pytun`
