### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by ramiil** [montag451/pytun#15]
I have error while install using pip.

```
c:\py3\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\py3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ramiil\\AppData\\Local\\Temp\\pip-build-7l07d56t\\python-pytun\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ramiil\AppData\Local\Temp\pip-83dn8uqm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ramiil\AppData\Local\Temp\pip-build-7l07d56t\python-pytun\
```

I think I have solution, but I haven't tested it yet.

Solution:
    Download(http://www.microsoft.com/en-us/download/details.aspx?id=3138) and install Microsoft Windows SDK for Windows 7 and .NET Framework 3.5 SP1. You will need only:
        Developer Tools > Windows Headers and Libraries <-- this gives you basetsd.h
        Developer Tools > Visual C++ Compilers <-- this gives you the 64-bit compilers

From here - https://stackoverflow.com/questions/23691564/running-cython-in-windows-x64-fatal-error-c1083-cannot-open-include-file-ba

**Comment by montag451** [comment]
Windows is not supported, sorry :(
