### ISSUE TITLE
Closing device does not unblock the read call

### ISSUE THREAD

**Issue by lucas-bremond** [montag451/pytun#18]
What is the recommended way to tear down the process when the thread is locked waiting for `buf = tun.read(tun.mtu)`?

I was hoping that closing the device using `tun.close()` from another thread would make the `read` return an empty buffer, therefore allowing to `join` the reception thread, but that does not seem to be the case.

Is using `select` the way to go here?

Any idea?

Thanks!

**Comment by montag451** [comment]
Hi @lucas-bremond,

Sorry for the late reply. Unfortunately there is nothing I can do on my side to solve this problem. The only solution I can think of is indeed to use select. Something like that should solve your problem :
``` python
import os
import selectors
import threading
import time

import pytun  # type: ignore


def close_tun(tun: pytun.TunTapDevice, sleep_time: int = 5) -> None:
    time.sleep(sleep_time)
    tun.close()
    print("TUN/TAP device closed")


def main() -> None:
    tun = pytun.TunTapDevice()
    os.set_blocking(tun.fileno(), False)
    selector = selectors.DefaultSelector()
    selector.register(tun, selectors.EVENT_READ)
    th = threading.Thread(target=close_tun, args=(tun,))
    th.start()
    while tun.fileno() != -1:
        events = selector.select(timeout=1)
        # Process events... (here I only print the events that occurred)
        print(events)
    th.join()


if __name__ == "__main__":
    main()
```

**Comment by lucas-bremond** [comment]
Works well, thank you Sir!

**Comment by montag451** [comment]
You are welcome!
