### ISSUE TITLE
when create a tap device and set it, ping this machine failed

### ISSUE THREAD

**Issue by leavky** [montag451/pytun#20]
Hello, when i create a tap device and config it's. But why can't ping this machine.
`tap = TunTapDevice(name="my_tap_0", flags=IFF_TAP)
tap.addr = '10.10.10.117'
tap.dstaddr = '10.10.10.10'
tap.netmask = '255.255.255.0'
tap.mtu = 1500

#tap.persist(True)
tap.up()

while True:
  packet = tap.read(1024)
  print(packet)`

![image](https://user-images.githubusercontent.com/46547390/117577090-f3a6e800-b11a-11eb-884e-c2a927749791.png)

why ping `10.10.10.10`  failed, please.

**Comment by montag451** [comment]
I don't think it is a problem with `pytun` but that it is related to your setup so I will close this issue. Feel free to re-open if you don't agree.
