### ISSUE TITLE
Provide Python 3.10/3.11 wheels (+musllinux)

### ISSUE THREAD

**Issue by ben9923** [montag451/pytun#22]
Hey :)

It would be cool to have wheels for Python 3.10 that's around for a while, and 3.11 while we're at it (It's now ABI stable).
It would also be really nice to have `musllinux` wheels, which seem to be provided by almost every (maintained) package now.

I'm planning on adding a CI script in a PR to build all of those, to make it super easy to do so.
There's no need for a new release, just uploading the 'diff' to PyPI, as apparently the latest release matches `master`.

Thanks for your work!

**Comment by montag451** [comment]
Hi @ben9923,

I've uploaded all the requested wheels. Please check and if it's OK for you I will close this issue.

**Comment by ben9923** [comment]
@montag451 Looks great, thank you so much!

**Comment by montag451** [comment]
Yes I've uploaded too much wheels indeed :smile: but as you said it should not cause any harm. I will close this issue. Thanks again for your contribution, it's greatly appreciated :+1:
