### ISSUE TITLE
Error writing bytes

### ISSUE THREAD

**Issue by teraa** [montag451/pytun#24]
I guess this is more of a question. I created a persistent tun device with e.g.
```
ip tuntap add dev tun0 mode tun user tera
ip address add dev tun0 10.20.0.1/24
ip link set dev tun0 up
```

a simple program:
```py
import pytun

tun = pytun.TunTapDevice('tun0')
buf = b'foo'
tun.write(buf)
```
when trying to write bytes, most of the time I get the following error
> pytun.Error: [Errno 22] Invalid argument

What's the issue here? How are you supposed to write raw bytes? (Disregarding where they come from, for now)

**Comment by montag451** [comment]
You can't write arbitrary data inside a TUN/TAP device. You need to write IP packets inside TUN device or IP packet with layer 2 header in case of TAP device.

**Comment by teraa** [comment]
Oh that makes sense, thanks for quick answer

**Comment by montag451** [comment]
> Oh that makes sense, thanks for quick answer

You are welcome!
