### ISSUE TITLE
ImportError: cannot import name TunTapDevice

### ISSUE THREAD

**Issue by binaryer** [montag451/pytun#4]
[root@centos python-pytun-2.1]# python -V
Python 2.6.6

[root@centos python-pytun-2.1]# python setup.py install
running install
running build
running build_ext
building 'pytun' extension
creating build
creating build/temp.linux-x86_64-2.6
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c pytun.c -o build/temp.linux-x86_64-2.6/pytun.o
creating build/lib.linux-x86_64-2.6
gcc -pthread -shared build/temp.linux-x86_64-2.6/pytun.o -L/usr/lib64 -lpython2.6 -o build/lib.linux-x86_64-2.6/pytun.so
running install_lib
copying build/lib.linux-x86_64-2.6/pytun.so -> /usr/lib64/python2.6/site-packages
running install_egg_info
Writing /usr/lib64/python2.6/site-packages/python_pytun-2.1-py2.6.egg-info

[root@centos python-pytun-2.1]# cat mytest.py
from pytun import TunTapDevice
tun = TunTapDevice()

[root@centos python-pytun-2.1]# python mytest.py
Traceback (most recent call last):
  File "mytest.py", line 1, in <module>
    from pytun import TunTapDevice
  File "/root/Desktop/python-pytun-2.1/mytest.py", line 1, in <module>
    from pytun import TunTapDevice
ImportError: cannot import name TunTapDevice

**Comment by ysangkok** [comment]
Seems that you get this problem if you pip install pytun instead of python-pytun.

**Comment by montag451** [comment]
Yeah, there is another project with the same name, I should add a warning in the documentation.
