### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by davidahoward** [montag451/pytun#5]
The current release does not support IPv6 TUN interfaces.
I'd be happy to help/create this support, but could use some direction as to naming convention for parameters, etc...

**Comment by montag451** [comment]
Hi davidahoward, it would be great if you could add support for IPv6. Regarding your question about the coding style, the best thing I think is to start to look at my code. You could start to implement the IPv6 support and then send me push request and if something is wrong with the coding style, I will let you know :)

**Comment by jersobh** [comment]
It would be noice
