### ISSUE TITLE
outdated doc

### ISSUE THREAD

**Issue by zoobab** [montag451/pytun#7]
Hi,

The doc you have might be outdated, the TunTap examples cannot be found if I install pytun via pip:

>>> from pytun import TunTapDevice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name TunTapDevice

In [2]: pytun.
pytun.TUN_KO_PATH  pytun.TunTunnel    pytun.fcntl        pytun.logger       pytun.open         pytun.struct
pytun.TapTunnel    pytun.Tunnel       pytun.functools    pytun.logging      pytun.os           pytun.tunnel

**Comment by montag451** [comment]
You have installed the wrong package. Use: 
 ```
pip install python-pytun
```
